name: Deploy React App to Timeweb
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches: [main, dev]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Build React app (Vite)
        run: npm run build

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy to Timeweb
        run: |
          # Выбираем путь в зависимости от ветки
          if [ "${{ github.ref_name }}" = "main" ]; then
            TARGET_DIR="/home/c/cy20187/web-use/public_html"
          else
            TARGET_DIR="/home/c/cy20187/dev.web-use/public_html"
          fi

          # Создаём папку, если её нет
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -p ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "mkdir -p $TARGET_DIR"

          # Деплоим содержимое папки dist (НЕ build!)
          sshpass -p "${{ secrets.SSH_PASSWORD }}" rsync -avz --delete \
            --exclude '.git*' \
            --exclude 'node_modules' \
            --exclude '.env' \
            -e "ssh -p ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=no" \
            ./dist/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:$TARGET_DIR/
